### PR TITLE
update instructions

### PR DESCRIPTION
**Pull request by fedorov**
@pieper is this right?

### CODE REVIEW

**Comment by pieper** [comment]
Yes, you are right.  But its also probably okay to leave out that step and just configure the xserver before ever ever running it.

**Comment by fedorov** [comment]
So should that line be removed altogether?

**Comment by pieper** [comment]
I haven't tried - maybe X needs to run once before the nvidia command works, but I think not.  In any case it would need to be killed and restarted after the gpu is configured.

**Comment by fedorov** [comment]
I replicated the content into this repository to have a more focused place to develop this content: https://github.com/QIICR/SlicerGCPSetup.

@pieper @che85 if you would rather keep doing it here, let me know.

**Comment by pieper** [comment]
Make sense - I was going to suggest the same thing.

**Pull request closed without merging**
