### PR TITLE
Adding PW29

### PR DESCRIPTION
**Pull request by adamrankin**
Minor typos in TLD

### CODE REVIEW

**Comment by hmeine** [comment]
Apparently, there are two summer project weeks this year?  Should the pages mention that / differentiate between them?

**Comment by jcfr** [comment]
May be a reference could be added to the top level README: https://github.com/NA-MIC/ProjectWeek/blob/master/README.md ? 

also wondered if the numbering should be switched ... 28th -> 29th, and 29th -> 28th

**Comment by adamrankin** [comment]
I clarified in the top-level readme, and I went by dates for numbering.

**Comment by adamrankin** [comment]
Also, I don't mind having a completely different numbering system.
We are definitely not hurt if this is identified as Satellite Week #2 or Project Week Western #2 (etc...)

**Pull request merged**
