### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by HUTIN1**

### CODE REVIEW

**Comment by sjh26** [comment]
@HUTIN1 Could you
- remove the space in the folder name
- update the `project_title` and `category` at the top of the readme file

**Comment by sjh26** [comment]
you can also just put the needed info in a comment and i can update the PR

**Comment by HUTIN1** [comment]
@sjh26 
Thanks for your help.
I followed your instructions and updated as you asked.

**Comment by sjh26** [comment]
good to go now, thanks!

**Pull request merged**
