### PR TITLE
[DRAFT] MHub integration project

### PR DESCRIPTION
**Pull request by LennyN95**

### CODE REVIEW

**Comment by pieper** [comment]
Looks like a great project 👍 

It could be good to identify a few segmentation models that you expect to be supported so that we can use them to evaluate success.  In addition to TotalSegmentator, I would suggest [SynthSeg](https://github.com/BBillot/SynthSeg), SynthStrip, SynthSR.  Also would be good to know how to export models trained with MONAI Label into MHub (perhaps using [MONAI Deploy / MAP](https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/developing_with_sdk/executing_packaged_app_locally.html)). 

As a stretch goal it would be good to look at how to wrap registration networks like [voxelmorph](https://github.com/voxelmorph/voxelmorph).

**Comment by fedorov** [comment]
> It could be good to identify a few segmentation models that you expect to be supported so that we can use them to evaluate success. 

Completely agree! Although, to manage the scope, I would suggest we use the models that are already in MHub (Dennis and Leo will already have a lot to learn, and it may be too much to integrate yet another new model on top of that). Among those already in MHub, we could pick one of the nnU-Net models, as an example.

**Comment by LennyN95** [comment]
Thank you @fedorov and @pieper for your comments, sounds like a solid plan.

As @fedorov suggested, we will start learning and working on slicer integration based on the models we have already worked on standardizing.
Since our goal is to create a generic wrapper, this will not preclude adding future models as you suggested, @pieper.
Besides learning how to create slicer integrations in the first place, we will first focus on gathering information about the best approach (Docker / venv / ...), as each approach has pros and cons that also depend on the target community.

As a side note, the "How to create a project" page still refers to PW37 (which I fell for :D).

**Comment by pieper** [comment]
> As a side note, the "How to create a project" page still refers to PW37 (which I fell for :D).

Thanks for pointing this out!  Fixed in https://github.com/NA-MIC/ProjectWeek/commit/3ae0ade7d2808567c537d6fb0df008747f71eef0

**Comment by fedorov** [comment]
Per discussion with @denbonte and @LennyN95, merging this initial version, will refine further.

**Pull request merged**
