### PR TITLE
Update participants list. 2022-11-15

### PR DESCRIPTION
**Pull request by piiq**
Auto generated PR

### CODE REVIEW

**Comment by piiq** [comment]
@jcfr netlify is complaining about a deprecated version of ubuntu. I didn't find any CI configs in this repo 🤷‍♂️. Is there anything I can to to update the actions?

image

**Comment by jcfr** [comment]
Thanks for pointing this out, I will update the netlify configuration later today.

**Comment by jcfr** [comment]
The build image associated with netlify has been updated from Ubuntu 16.04 to 20.04. 

For reference:
* https://github.com/netlify/build-image/commit/849f9040512a5b4c99a4adb5e72809d6fde5819e: `Remove Xenial references in the repo`
* https://docs.netlify.com/configure-builds/overview/#build-image-selection

image

**Comment by jcfr** [comment]
Merging. Indeed, after manually re-triggering the build on netlify and inspecting the [preview](https://637551cec196ad46f69e0048--projectweek-na-mic-org-preview.netlify.app/pw38_2023_grancanaria/), I was able to to confirm the changes are valid.

image

**Pull request merged**
