### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by agopu**
Adding our project per Simon/Tina's advice in the PW prep zoom call this week.

### CODE REVIEW

**Comment by drouin-simon** [comment]
Please remember to also create a link to this page on the main project page.

**Comment by drouin-simon** [comment]
Oups! I just realized after merging that you created a page in PW 33 instead of PW 34

**Comment by agopu** [comment]
@drouin-simon 

> Oups! I just realized after merging that you created a page in PW 33 instead of PW 34

I noticed that belatedly but I was just following the links on your instructions page. Should I move the link to PW34 or have you already done that perhaps? Thanks!

**Comment by agopu** [comment]
Never mind @drouin-simon I just now redid the process and did another PR on PW34. Could you please approve it? Thank you!

Feel free to remove this sub-dir in PW33 completely if you prefer.

**Comment by drouin-simon** [comment]
Thanks Arvind. I will change the link in the instruction page.

**Pull request merged**
