### PR TITLE
Adding project page for London 2019 project week

### PR DESCRIPTION
**Pull request by adamrankin**
Renumbering project weeks to correspond with chronological order

### CODE REVIEW

**Comment by jcfr** [comment]
Looks good to me.

@tkapur What do you think ?

**Comment by tkapur** [comment]
Looks good overall. Why is the google calendar not embedded?

**Comment by adamrankin** [comment]
Does that work now? As of last year it didn't work, and I just copied from last year.

**Comment by tkapur** [comment]
Take a look at the bottom of this page.  It works:

https://na-mic.github.io/ProjectWeek/PW30_2019_GranCanaria/

**Comment by lassoan** [comment]
Calendar does not show up in github preview but works well on the generated pages.

**Comment by adamrankin** [comment]
Aha! Ok, will fix that.

**Comment by tkapur** [comment]
After that please go ahead and renumber the subsequent project week.

**Comment by adamrankin** [comment]
The subsequent project week was renumbered as part of the original commit. Did I miss a spot?

**Comment by tkapur** [comment]
https://github.com/NA-MIC/ProjectWeek/tree/master/PW32_2020_GranCanaria

**Comment by adamrankin** [comment]
Any other changes?

**Pull request merged**
