### PR TITLE
Add 4 DICOM projects

### PR DESCRIPTION
**Pull request by fedorov**
@hmeine @pieper @hackermd FYI

Hans, I do not know git login of Peter Oppermann, can you mention him?

### CODE REVIEW

**Comment by fedorov** [comment]
cc @JamesDarcy616 @JamesAPetts

**Comment by JamesAPetts** [comment]
Added another project that is in a few of our shared interested, feel free to add you name.

**Comment by pieper** [comment]
Looks good to me.  @tkapur do you mind if we merge this onto the project week page and start updating there?

**Comment by tkapur** [comment]
perfect!

**Comment by fedorov** [comment]
Great, thanks. We can merge some of those projects later, if we decide that would be more efficient to present and maintain.

**Comment by PeterOpp** [comment]
> @hmeine @pieper @hackermd FYI
> 
> Hans, I do not know git login of Peter Oppermann, can you mention him?

Here I am

**Pull request merged**
