### PR TITLE
PW39_2023_Montreal: Improve project template

### PR DESCRIPTION
**Pull request by jcfr**
* Introduce front-matter variables "project_title" and "key_investigators"
* Add "pw39_project.html" layout

### CODE REVIEW

**Comment by jcfr** [comment]
The following error is reported:

> 4:16:57 PM:      Build Warning: Layout 'pw39-project' requested in PW39_2023_Montreal/Projects/Template/README.md does not exist.

**Comment by jcfr** [comment]
Look there is still an issue with the layout:

image

**Comment by jcfr** [comment]
One last issue related to affiliation:

image

**Comment by jcfr** [comment]
Et voila:

image

**Comment by sjh26** [comment]
lgtm!

**Pull request merged**
