### PR TITLE
PW40_2024_GranCanaria: Add "Other" as a project category

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Since we already have "Uncategorized" category used as a catch all category, should we still include this ?

**Comment by jcfr** [comment]
Should we also list `Early Presenter` in the pull request template ?

**Comment by sjh26** [comment]
I think it is good to include it, since you can't see the 'Uncategorized' from the issue template, and so you aren't sure what to select.  You can always edit the category later.

Re: early presenter, probably not.  People generally aren't sure this far out what their schedule will look like day of.

**Comment by sjh26** [comment]
Uncategorized is more of an error catch than an actual category.  Most of the time in the last project week it was catching typo'd categories from pages created directly from the template

**Review by sjh26 — APPROVED** [review]
looks good

**Pull request merged**
