### PR TITLE
Add "Edit me on GitHub" banner

### PR DESCRIPTION
**Pull request by ihnorton**
Preview: https://ihnorton.github.io/ProjectWeek

Banner is available (and correctly linked) on all pages.

### CODE REVIEW

**Comment by jcfr** [comment]
"Edit me on GitHub" -> "Edit this page on GitHub" ?

**Comment by jcfr** [comment]
It also looks like we lost the formatting (centered page, list styling, spacing, ... )

**Comment by jcfr** [comment]
An other nice improvement would be to render an "anchor" near each section. May be something like this: https://milanaryal.com/adding-hover-anchor-links-to-header-on-github-pages-using-jekyll/

**Comment by jcfr** [comment]
Looks like http://necolas.github.io/normalize.css/ is currently used to render GitHub page

**Comment by jcfr** [comment]
* Anchor js is what is used on the current page:

current-wiki-page

* And here where I found the reference to normalize css:

screenshot from 2017-12-12 17-42-59

**Comment by ihnorton** [comment]
Thanks for the link. It looks like customizing jekyll layouts like this will break the auto-rendering for `README.md` files, but there is a plugin to fix that.

I'll take a look again later today and fix the stylesheet issues, and make sure all of the links still work (unless you want to edit the branch, feel free).

**Comment by jcfr** [comment]
> I'll take a look again later today and fix the stylesheet issues, and make sure all of the links still work (unless you want to edit the branch, feel free).

I don't think I will have time to work on it. Instead, I will continue to improve the import script for migrating existing pages from wiki to GitHub.

**Comment by lassoan** [comment]
Thanks for working on this. It is really helpful to see the edit links only on the rendered project pages (as the links did not work when used in github's preview, and that confused people).

Just a small comment: For me, the large red slanted banner is a bit too prominent. I would prefer something more subtle, such as just a horizontal banner or button in the corner.

**Comment by ihnorton** [comment]
For future reference, the current theme (github pages default) is: https://github.com/pages-themes/primer

**Comment by ihnorton** [comment]
Is this better?
image

Or you don't like the size, period? If the latter, I'm not going to spend more time on this but we can easily add just link to the default theme so it shows up: somewhere customizable, automatically, and only on the rendered page.

**Comment by ihnorton** [comment]
I updated this PR with a much smaller change-set: just customizing the default github-pages theme (now that I know what it is) so everything else should stay the same. Also included the change to make the ribbon gray, so now you can see that rendered here:

https://ihnorton.github.io/ProjectWeek/

**Comment by ihnorton** [comment]
(ok now the link actually works 😄 )

**Comment by lassoan** [comment]
I like the gray color better, but I think my main issue is that it is a slanted ribbon. Why not just a plain horizontal button in the corner? It would take up less space and if we wanted, then we could also add other buttons there (for example, jump back to project list or project home page)

**Comment by jcfr** [comment]
I agree we could improve further. That said, I suggest we move forward with that first set of changes since it address the initial issue.

**Comment by lassoan** [comment]
Fully agree, this tweaking should not hold up the merge.

**Comment by jcfr** [comment]
Later, may be the fixed bar from this theme could be reused: https://pages-themes.github.io/midnight/ 

This were we could add things like: `Schedule | Participate | Venue & Local Info | Register                   Edit this page`

Idea from https://scipy2017.scipy.org/ehome/220975/493388/

**Comment by ihnorton** [comment]
Ok, merge for now. If people don't like it after a couple days then we can take out the fancy thing and just write a couple lines of CSS to put the link in the top-right.

**Comment by cpinter** [comment]
Just an additional opinion: I have seen this slanted banner many times, and I consider it kind of standard. So I think the gray one is fine.

**Pull request merged**
