### PR TITLE
Add cheap tracker project

### PR DESCRIPTION
**Pull request by pieper**

### CODE REVIEW

**Comment by traneus** [comment]
Steve:
Let me know if I can be of help.
Peter Traneus Anderson
 
-----Original Message-----
From: Steve Pieper ***@***.***>
To: NA-MIC/ProjectWeek ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Sun, Jan 16, 2022 5:29 pm
Subject: [NA-MIC/ProjectWeek] Add cheap tracker project (PR #358)


You can view, comment on, or merge this pull request online at:
  https://github.com/NA-MIC/ProjectWeek/pull/358
Commit Summary
   
   - 01aa111 Add cheap tracker project

File Changes 
 (1 file)   
   -  A PW36_2022_Virtual/Projects/CheapTracking/README.md (47) 

Patch Links:
   
   - https://github.com/NA-MIC/ProjectWeek/pull/358.patch
   - https://github.com/NA-MIC/ProjectWeek/pull/358.diff
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pieper** [comment]
Yo Peter! You are the perfect person for this project.  Let's think of all the technologies on the table and see if they can work together.

**Comment by traneus** [comment]
Steve:
I just registered for Virtual Project Week. Now I have to remember my github password. Technologies can certainly work together.
When I worked for General Electric, I learned the jargon: the entitlement of a technology. The entitlement is the performance to be expected if all the implementation details are done correctly. If the entitlement is not good enough, there is no need to invest in building the technology.
Inertial Measurement Units IMUs have two inherent defects:
1. The direction of the total acceleration is the sum of gravitational and mechanical accelerations. For small mechanical accelerations, the change in the direction of the total acceleration is proportional to the mechanical acceleration, but the change in the magnitude of the total acceleration is proportional to the square of the mechanical acceleration. Thus, mechanical accelerations too small to be detected in the magnitude can cause significant changes in the direction.
2. Position is two integrals away from acceleration, giving position drift which worsens over time.
IMUs have the advantages of fast response and good immunity to the presence of nearby objects, though ferromagnetic objects can affect the magnetic measurement.
Optical systems have the advantage of obviousness of how they work or don't work.

Magnetic trackers today have capabilities undreamed-of decades ago. Decades ago, the design goal was to minimize algorithm computation. Today computation is ridiculously cheap. For example, three decades ago, I replaced a circuit board of custom digital-to-analog converters with a matrix multiply in software.

 Magnetic tracker transmitters can interfere with flat-panel Xray detectors.
PeteTA
 
-----Original Message-----

**Comment by pieper** [comment]
Hi Pete -

Those are all great points 👍 

I agree about IMUs alone, but in the context of sensor fusion with cameras and depth scanners they seem to work okay in practice to provide good overall tracking (for certain values of "good").

I would love it if we could provide an open hardware solution for sterilizable EM trackers for NousNav.

Nice thing about the WebXR technology is that it's easy to test using a regular smartphone.  Thinking a bit, it's possible that the phone also uses EM, since it has lots of antennas after all.

**Comment by traneus** [comment]
Steve:
Yes, sensor fusion can alleviate IMU limitations: IMU provides rapid response, and other sensors correct drifts.

https://osf.io/47q8q/wiki/home/anser.io is an open-source EM catheter-tracking project using a single-coil sensor. I learned about anser.io from Ole Vegard at PW31 in Boston in 2019. The project has a writeup of the electromagnetic theory.

A single-coil EM sensor cannot track roll about the sensor's axis. Instead, the sixth tracked quantity is the sensor's gain. This means that a single-coil sensor does not need to be characterized, so can be very cheap ($3.00 for the coil) and sterilizable. This is true also for tiny single-coil transmitters.
Using two single-coil sensors spaced apart perpendicular to their axes and/or pointed in different directions, would give roll while retaining single-coil advantages.
 
 If a catheter tip contains an electric motor, the motor's stray magnetic field may be trackable as a single-coil transmitter, though this would require deep integration of motor driver and EM tracker (perfect for open-source project).
An open-hardware EM tracker solution for NousNav is perfectly feasible, and highly desirable for algorithm transparency and customizability.
https://web.archive.org/web/20151002101401/http://home.comcast.net/~traneus/dry_emtrackertricoil.htmdiscusses the homemade 6DOF EM tracker I brought to Project Week a decade ago. Have your hardware people look at it and hear them respond, "This is trivial; we can do better than this!" Same for the software. The unfamiliar electromagnetics is easy to learn if you know basic calculus. The math of rotations using quaternions is familiar from the 3D-graphics world.

You do not need a robot to calibrate an EM tracker. A granite surface plate will suffice, except for an overall position scale factor provided by a ruler.

I wonder how deep this rabbit-hole is, and how many rabbits are down here?

 PeteTA
-----Original Message-----

**Comment by pieper** [comment]
Super info - thanks!

At this point we are just counting rabbit holes and guessing who deep they might be.  And whether they are likely to meet the 'entitlement' criterion.  Will you be able to join the Wednesday morning call to discuss with the group?

**Comment by traneus** [comment]
Steve:
I tried to figure out Discord, and it's too much for me and my laptop computer. I don't have equipment compatible with the Discord app. For computers, I have five-year-old Linux only, no Windows and no Mac. I can play audio through Firefox or Chromium web browser. It would take me a while to hook up a microphone, as my good microphone needs me to build a preamp for it. I do have landline telephone if there is a call-in number.
PeteTA
 
 
 
-----Original Message-----

**Comment by pieper** [comment]
Hi Pete, @traneus - 

Yes, here is the phone info for Wednesday at 10 eastern.

+1 646 558 8656 (New York)

Meeting ID: 862 1170 2920
Passcode: 409057

Oh here's link in case you can use it:

https://etsmtl.zoom.us/j/86211702920?pwd=TEl0ZTFDam90WVN5bjZhR05kNVRVZz09

**Comment by traneus** [comment]
Thanks! 
 
 
-----Original Message-----

**Comment by traneus** [comment]
Steve:
Thanks for the telephone-connection info. I enjoyed the two hours of conversation. It confirmed my observation from 2018 that, if optical tracking is feasible then optical is the way to go.
Teflon-insulated cables should be able to withstand thermal-sterilization temperatures. Teflon non-stick cooking-pan coatings do work.
Thanks again. PeteTA 
-----Original Message-----

**Comment by pieper** [comment]
So glad you were able to join and thanks for all your insights today @traneus !  take care, Steve

**Pull request merged**
